# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

b = Business.create(:name => "Jeffrey's Smorgasbord", :tagline => "It's smorgalicious!",
                    :footnotes => "<p>Food has been known to cause girth.</p><p>It might be against the law in some countries to prepare raw meat. Just sayin'.</p><p>Parties of 30 or more should go somewhere else.</p>",
                    :address_1 => "123 Numbers St.", :city => "Washington", :state => "DC", :postal_code => "99999")
vegetarian = Tag.create(:business => b, :name => "Vegetarian", :description => "Doesn't bleed")
m = Menu.create(:business => b, :name => "Dinner", :start_time => Time.gm(0,1,1,17), :end_time => Time.gm(0,1,1,22))
appetizers = Category.create(:menu => m, :name => "Appetizers", :order => 0)
caesar = Item.create(:business => b, :name => "Caesar Salad", :description => "Now with lettuce", :tags => [vegetarian])
Placement.create(:category => appetizers, :item => caesar, :price => 8, :order => 0)
onion_soup = Item.create(:business => b, :name => "Onion Soup", :description => "Onions, now in soup form", :tags => [vegetarian])
Placement.create(:category => appetizers, :item => onion_soup, :price => 8, :order => 1)
mussels = Item.create(:business => b, :name => "Mussels", :description => "They're not alive like oysters")
Placement.create(:category => appetizers, :item => mussels, :price => 10, :order => 2)
mains = Category.create(:menu => m, :name => "Mains", :order => 1)
portobello_sandwich = Item.create(:business => b, :name => "Portobello Sandwich", :description => "Realized we didn't have any vegetarian options", :tags => [vegetarian])
Placement.create(:category => mains, :item =>portobello_sandwich, :price => 12, :order => 0)
pork_tenderloin = Item.create(:business => b, :name => "Pork Tenderloin", :description => "It's porky and loiny")
Placement.create(:category => mains, :item => pork_tenderloin, :price => 18, :order => 1)
filet_mignon = Item.create(:business => b, :name => "Filet Mignon", :description => "It doesn't have beef in the title, but that's what it is")
Placement.create(:category => mains, :item => filet_mignon, :price => 23, :order => 2)
half_chicken = Item.create(:business => b, :name => "Half Chicken", :description => "We give the other half to charity")
Placement.create(:category => mains, :item => half_chicken, :price => 16, :order => 3)
dessert = Category.create(:menu => m, :name => "Dessert", :order => 2)
creme_brulee = Item.create(:business => b, :name => "Creme Brulee", :description => "Too lazy to add accents properly", :tags => [vegetarian])
Placement.create(:category => dessert, :item => creme_brulee, :price => 7, :order => 0)
chocolate_mousse = Item.create(:business => b, :name => "Chocolate Mousse", :description => "The antlers are not edible")
Placement.create(:category => dessert, :item => chocolate_mousse, :price => 7, :order => 1)
fruit_tart = Item.create(:business => b, :name => "Fruit Tart", :description => "Pretend you're health-conscious", :tags => [vegetarian])
Placement.create(:category => dessert, :item => fruit_tart, :price => 6, :order => 2)
sides = Category.create(:menu => m, :name => "Sides", :order => 3, :start_time => Time.gm(0,1,1,17), :end_time => Time.gm(0,1,1,20))
beans = Item.create(:business => b, :name => "Beans", :description => "*toot*", :tags => [vegetarian])
Placement.create(:category => sides, :item => beans, :price => 3, :order => 0)
mac_cheese = Item.create(:business => b, :name => "Mac and Cheese", :description => "This coming from a restaurant that serves creme brulee", :tags => [vegetarian])
Placement.create(:category => sides, :item => mac_cheese, :price => 5, :order => 1)
coleslaw = Item.create(:business => b, :name => "Coleslaw", :description => "Only the finest iceberg and mayonnaise", :tags => [vegetarian])
Placement.create(:category => sides, :item => coleslaw, :price => 3, :order => 2)
beverages = Category.create(:menu => m, :name => "Beverages", :order => 4)
butterbeer = Item.create(:business => b, :name => "Butterbeer", :description => "Did we mention we're wizards?")
Placement.create(:category => beverages, :item => butterbeer, :price => 4, :order => 0)
root_beer = Item.create(:business => b, :name => "Root Beer", :description => "A different kind of root every day")
Placement.create(:category => beverages, :item => root_beer, :price => 3, :order => 1)
beer = Item.create(:business => b, :name => "Beer", :description => "Not like the other beers")
Placement.create(:category => beverages, :item => beer, :price => 5, :order => 2)